insert into `COMPANY` (`name`, `location`) values ('Yamia', '57 Katie Court');
insert into `COMPANY` (`name`, `location`) values ('Podcat', '8 Lighthouse Bay Terrace');
insert into `COMPANY` (`name`, `location`) values ('Rhyloo', '3 Old Gate Road');
insert into `COMPANY` (`name`, `location`) values ('Rhyzio', '0 Commercial Lane');
insert into `COMPANY` (`name`, `location`) values ('Oyoloo', '52 Esker Circle');
insert into `COMPANY` (`name`, `location`) values ('Twinder', '808 Clove Avenue');
insert into `COMPANY` (`name`, `location`) values ('Blogspan', '4978 Gina Street');
insert into `COMPANY` (`name`, `location`) values ('Abatz', '90306 Meadow Vale Plaza');
insert into `COMPANY` (`name`, `location`) values ('Trunyx', '62 Menomonie Point');
insert into `COMPANY` (`name`, `location`) values ('Fadeo', '520 Morning Road');
insert into `COMPANY` (`name`, `location`) values ('Jabbertype', '4 Mayer Park');
insert into `COMPANY` (`name`, `location`) values ('Dablist', '9921 Thackeray Center');
insert into `COMPANY` (`name`, `location`) values ('Mydeo', '32 Toban Place');
insert into `COMPANY` (`name`, `location`) values ('Yacero', '7 Larry Park');
insert into `COMPANY` (`name`, `location`) values ('Jetwire', '077 Esch Place');
insert into `COMPANY` (`name`, `location`) values ('Thoughtstorm', '878 Cambridge Park');
insert into `COMPANY` (`name`, `location`) values ('Jabbercube', '153 5th Place');
insert into `COMPANY` (`name`, `location`) values ('Skyble', '68694 Holy Cross Place');
insert into `COMPANY` (`name`, `location`) values ('Bubblemix', '9947 Forest Court');
insert into `COMPANY` (`name`, `location`) values ('Bubblemix', '9480 Mitchell Point');
insert into `COMPANY` (`name`, `location`) values ('Skyndu', '02749 Nevada Plaza');
insert into `COMPANY` (`name`, `location`) values ('Oodoo', '1407 Park Meadow Trail');
insert into `COMPANY` (`name`, `location`) values ('LiveZ', '103 Farmco Point');
insert into `COMPANY` (`name`, `location`) values ('Eabox', '44 Montana Trail');
insert into `COMPANY` (`name`, `location`) values ('Mynte', '38 Pond Court');
insert into `COMPANY` (`name`, `location`) values ('Rhybox', '52 Darwin Lane');
insert into `COMPANY` (`name`, `location`) values ('Twinder', '85 Huxley Center');
insert into `COMPANY` (`name`, `location`) values ('Skyble', '92977 Clove Avenue');
insert into `COMPANY` (`name`, `location`) values ('Babbleset', '58491 Farwell Point');
insert into `COMPANY` (`name`, `location`) values ('Lazzy', '26632 Ilene Parkway');
insert into `COMPANY` (`name`, `location`) values ('Skyble', '46 Bayside Place');
insert into `COMPANY` (`name`, `location`) values ('Fivespan', '89 High Crossing Court');
insert into `COMPANY` (`name`, `location`) values ('Buzzshare', '1 Huxley Center');
insert into `COMPANY` (`name`, `location`) values ('Centimia', '0390 Talisman Hill');
insert into `COMPANY` (`name`, `location`) values ('Wikibox', '9 Di Loreto Crossing');
insert into `COMPANY` (`name`, `location`) values ('Yakitri', '26998 Paget Circle');
insert into `COMPANY` (`name`, `location`) values ('Bluezoom', '6 Rowland Junction');
insert into `COMPANY` (`name`, `location`) values ('Twitterbeat', '7465 Sunfield Place');
insert into `COMPANY` (`name`, `location`) values ('Dynabox', '782 Scofield Way');
insert into `COMPANY` (`name`, `location`) values ('Oyondu', '90 Ridgeview Place');
insert into `COMPANY` (`name`, `location`) values ('Jamia', '98 Hovde Road');
insert into `COMPANY` (`name`, `location`) values ('Brightdog', '803 Commercial Park');
insert into `COMPANY` (`name`, `location`) values ('Trudeo', '457 David Parkway');
insert into `COMPANY` (`name`, `location`) values ('Devpulse', '6 Browning Lane');
insert into `COMPANY` (`name`, `location`) values ('Pixope', '44716 Daystar Place');
insert into `COMPANY` (`name`, `location`) values ('Vinder', '3006 Bowman Road');
insert into `COMPANY` (`name`, `location`) values ('Youspan', '298 Delladonna Way');
insert into `COMPANY` (`name`, `location`) values ('Gabtype', '90685 La Follette Alley');
insert into `COMPANY` (`name`, `location`) values ('Gigashots', '9 Dorton Street');
insert into `COMPANY` (`name`, `location`) values ('Agimba', '64936 Lotheville Junction');
insert into `COMPANY` (`name`, `location`) values ('Photofeed', '90 5th Center');
insert into `COMPANY` (`name`, `location`) values ('Buzzdog', '73 Marquette Avenue');
insert into `COMPANY` (`name`, `location`) values ('Bubbletube', '54343 Pond Way');
insert into `COMPANY` (`name`, `location`) values ('Kare', '17 Emmet Place');
insert into `COMPANY` (`name`, `location`) values ('Quire', '76560 Lillian Center');
insert into `COMPANY` (`name`, `location`) values ('Ooba', '89388 Arrowood Center');
insert into `COMPANY` (`name`, `location`) values ('Pixope', '9 Sachs Hill');
insert into `COMPANY` (`name`, `location`) values ('Linkbuzz', '32917 Bobwhite Junction');
insert into `COMPANY` (`name`, `location`) values ('Voomm', '4869 Lake View Street');
insert into `COMPANY` (`name`, `location`) values ('Riffpedia', '53919 Melody Lane');
insert into `COMPANY` (`name`, `location`) values ('Gevee', '902 Basil Junction');
insert into `COMPANY` (`name`, `location`) values ('Snaptags', '3116 Gerald Pass');
insert into `COMPANY` (`name`, `location`) values ('Zoonoodle', '39637 Gateway Street');
insert into `COMPANY` (`name`, `location`) values ('Ntag', '685 Prairie Rose Parkway');
insert into `COMPANY` (`name`, `location`) values ('Shuffletag', '23819 Mallory Center');
insert into `COMPANY` (`name`, `location`) values ('Skinte', '98 Scofield Center');
insert into `COMPANY` (`name`, `location`) values ('Devcast', '0 Talmadge Trail');
insert into `COMPANY` (`name`, `location`) values ('Janyx', '306 Kropf Point');
insert into `COMPANY` (`name`, `location`) values ('Wikivu', '6 Thompson Point');
insert into `COMPANY` (`name`, `location`) values ('Feedfire', '7 Dixon Hill');
insert into `COMPANY` (`name`, `location`) values ('Yakitri', '42 Utah Point');
insert into `COMPANY` (`name`, `location`) values ('Jabbersphere', '3 Susan Alley');
insert into `COMPANY` (`name`, `location`) values ('Jamia', '02831 Schurz Parkway');
insert into `COMPANY` (`name`, `location`) values ('Skippad', '0 Vahlen Center');
insert into `COMPANY` (`name`, `location`) values ('Skimia', '3367 Sommers Trail');
insert into `COMPANY` (`name`, `location`) values ('Zoomdog', '26 Arkansas Drive');
insert into `COMPANY` (`name`, `location`) values ('Riffpath', '5141 Bay Trail');
insert into `COMPANY` (`name`, `location`) values ('Katz', '523 Declaration Avenue');
insert into `COMPANY` (`name`, `location`) values ('Jaxworks', '647 Homewood Plaza');
insert into `COMPANY` (`name`, `location`) values ('Twitterlist', '30670 Hayes Trail');
insert into `COMPANY` (`name`, `location`) values ('Oozz', '1580 Spohn Crossing');
insert into `COMPANY` (`name`, `location`) values ('Blogpad', '86702 Donald Pass');
insert into `COMPANY` (`name`, `location`) values ('Feednation', '1 Autumn Leaf Road');
insert into `COMPANY` (`name`, `location`) values ('Devcast', '2 Clyde Gallagher Parkway');
insert into `COMPANY` (`name`, `location`) values ('Fivespan', '92934 Mcguire Point');
insert into `COMPANY` (`name`, `location`) values ('Eidel', '05326 Kedzie Plaza');
insert into `COMPANY` (`name`, `location`) values ('Quimm', '1 Lillian Crossing');
insert into `COMPANY` (`name`, `location`) values ('Divape', '521 Rowland Circle');
insert into `COMPANY` (`name`, `location`) values ('Skivee', '6492 Del Mar Terrace');
insert into `COMPANY` (`name`, `location`) values ('Browseblab', '3 Veith Lane');
insert into `COMPANY` (`name`, `location`) values ('Lazz', '757 Bunker Hill Plaza');
insert into `COMPANY` (`name`, `location`) values ('Plajo', '7 Washington Avenue');
insert into `COMPANY` (`name`, `location`) values ('Topiclounge', '4458 Victoria Street');
insert into `COMPANY` (`name`, `location`) values ('Mynte', '88412 Vermont Place');
insert into `COMPANY` (`name`, `location`) values ('Zoomcast', '92 Fulton Junction');
insert into `COMPANY` (`name`, `location`) values ('Leexo', '77 Bonner Junction');
insert into `COMPANY` (`name`, `location`) values ('Voolia', '4 Derek Hill');
insert into `COMPANY` (`name`, `location`) values ('Feedfire', '419 Hudson Circle');
insert into `COMPANY` (`name`, `location`) values ('Trilia', '2 Continental Drive');
insert into `COMPANY` (`name`, `location`) values ('Thoughtblab', '728 Delaware Trail');